version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile:  "Dockerfile_$ENVIRONMENT"
    ports:
      - 8080:8080
    volumes:
      - ./client:/src
    user: "1000:1000"
  #      - ./client:/data
#    environment:
#      - API_URL=http://alexcristea.sytes.net:8081/
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - mongo_network
    ports:
      - 8081:8081
    depends_on:
      - mongo
    volumes:
      - ./server:/src
    user: "1000:1000"
#    environment:
#      DATABASE_URL: server-database

  mongo:
    image: mongo
#    command: mongod --auth
    networks:
      - mongo_network
    ports:
      - 27017:27017
    volumes:
#      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
      - ./db:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root
#      - MONGO_INITDB_DATABASE=apidb

volumes:
  db:

networks:
  mongo_network:
    driver: bridge